### ISSUE TITLE
SDRAM XSDS v2.9 decoupling issues

### ISSUE THREAD

**Issue by prrole** [MiSTer-devel/Hardware_MiSTer#17]
Pin 37 CKE is decoupled, while pin 1&3 VCC share a capacitor.  I assume this is a routing mistake as all 3 pins are labeled VCC.

74LVC1G04 could probably benefit from a decoupling capacitor as well.

**Comment by sorgelig** [comment]
pins 1&3 are very close to each other and have large polygon connected to both, so i don't think there will be any noticeable benefit for that. 
Pin 37 has capacitor not as CKE but as distributed capacitance since it's far from other capacitors.
For LVC1G04 - probably can connect its VCC to upper polygon and share the cap nearby. I will think about it if i will update the design
